#!/bin/bash

sudo yum install -y awscli jq

SECRET=$(aws secretsmanager get-secret-value --secret-id your-secret-id --query SecretString --output text)

DB_ADMIN_USERNAME=$(echo "${SECRET}" | jq -r '.db_admin.username')
DB_ADMIN_PASSWORD=$(echo "${SECRET}" | jq -r '.db_admin.password')
DB_ADMIN_HOST=$(echo "${SECRET}" | jq -r '.db_admin.host')
USER1_USERNAME=$(echo "${SECRET}" | jq -r '.user1.username')
USER1_PASSWORD=$(echo "${SECRET}" | jq -r '.user1.password')
USER2_USERNAME=$(echo "${SECRET}" | jq -r '.user2.username')
USER2_PASSWORD=$(echo "${SECRET}" | jq -r '.user2.password')

# Install packages and set up services
sudo yum -y update
sudo yum -y upgrade
sudo dnf install mariadb105-server -y
sudo dnf install -y httpd wget php-fpm php-mysqli php-json php php-devel
sudo systemctl start httpd
sudo systemctl enable httpd
sudo systemctl start mariadb
sudo systemctl enable mariadb
sudo usermod -a -G apache ec2-user
groups
sudo chown -R ec2-user:apache /var/www
sudo chmod 2775 /var/www && find /var/www -type d -exec sudo chmod 2775 {} \;
sudo chown -R ec2-user:apache /var/www/html
sudo chmod 2775 /var/www/html
find /var/www -type f -exec sudo chmod 0664 {} \;

# Automate mysql_secure_installation
sudo /bin/mysql_secure_installation <<EOF

y
y
${DB_ADMIN_PASSWORD}
${DB_ADMIN_PASSWORD}
y
y
y
y
EOF

# Create database and tables
sudo mysql -u root -p${DB_ADMIN_PASSWORD} <<EOF
CREATE USER '${DB_ADMIN_USERNAME}'@'${DB_ADMIN_HOST}' IDENTIFIED BY '${DB_ADMIN_PASSWORD}';
GRANT ALL PRIVILEGES ON links_app.* TO '${DB_ADMIN_USERNAME}'@'${DB_ADMIN_HOST}';
FLUSH PRIVILEGES;
CREATE DATABASE links_app;
USE links_app;
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);
INSERT INTO users (username, password) VALUES ('${USER1_USERNAME}', '${USER1_PASSWORD}'), ('${USER2_USERNAME}', '${USER2_PASSWORD}');
CREATE TABLE links (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    url VARCHAR(2083) NOT NULL,
    category VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)
);
EOF

# Download files from GitHub repo
sudo wget https://raw.githubusercontent.com/AntAntonov/links_app/main/config.php -O /var/www/html/config.php
sudo wget https://raw.githubusercontent.com/AntAntonov/links_app/main/index.php -O /var/www/html/index.php
sudo wget https://raw.githubusercontent.com/AntAntonov/links_app/main/login.php -O /var/www/html/login.php
sudo wget https://raw.githubusercontent.com/AntAntonov/links_app/main/main.php -O /var/www/html/main.php

sudo chown ec2-user:apache /var/www/html/config.php /var/www/html/index.php /var/www/html/login.php /var/www/html/main.php
sudo chmod 0664 /var/www/html/config.php /var/www/html/index.php /var/www/html

cd ~
sudo curl -sS https://getcomposer.org/installer | sudo php
sudo mv composer.phar /usr/local/bin/composer
sudo ln -s /usr/local/bin/composer /usr/bin/composer
cd /var/www/html
sudo composer require aws/aws-sdk-php
