#!/bin/bash
sudo yum -y update
sudo yum -y upgrade
sudo yum -y install python3 python3-pip
sudo dnf install mariadb105-server -y
sudo dnf install -y httpd wget php-fpm php-mysqli php-json php php-devel
sudo systemctl start httpd
sudo systemctl enable httpd
sudo systemctl start mariadb
sudo systemctl enable mariadb
sudo usermod -a -G apache ec2-user
groups
sudo chown -R ec2-user:apache /var/www
sudo chmod 2775 /var/www && find /var/www -type d -exec sudo chmod 2775 {} \;
find /var/www -type f -exec sudo chmod 0664 {} \;

# Automate mysql_secure_installation
sudo /bin/mysql_secure_installation <<EOF

y
y
Antikonti1
Antikonti1
y
y
y
y
EOF

# Create database and tables
sudo mysql -u root -pAntikonti1 <<EOF
CREATE USER 'antonov'@'localhost' IDENTIFIED BY 'Antikonti1';
GRANT ALL PRIVILEGES ON links_app.* TO 'antonov'@'localhost';
FLUSH PRIVILEGES;
CREATE DATABASE links_app;
USE links_app;
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);
INSERT INTO users (username, password) VALUES ('antonov', 'Antikonti1'), ('plamena', 'Antikonti1');
CREATE TABLE links (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    url VARCHAR(2083) NOT NULL,
    category VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)
);
EOF
# Download files from GitHub repo
sudo wget https://raw.githubusercontent.com/AntAntonov/links_app/main/config.php -O /var/www/html/config.php
sudo wget https://raw.githubusercontent.com/AntAntonov/links_app/main/index.php -O /var/www/html/index.php
sudo wget https://raw.githubusercontent.com/AntAntonov/links_app/main/login.php -O /var/www/html/login.php
sudo wget https://raw.githubusercontent.com/AntAntonov/links_app/main/main.php -O /var/www/html/main.php

sudo chown ec2-user:apache /var/www/html/config.php /var/www/html/index.php /var/www/html/login.php /var/www/html/main.php
sudo chmod 0664 /var/www/html/config.php /var/www/html/index.php /var/www/html/login.php /var/www/html/main.php
